name: Build and push image on Merge to Develop

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  build-and-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: maven

    - name: Build Project
      run: mvn clean install

    - name: Build & push Docker image
      if: ${{ success() }}
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: kkurella/user-management-service-image
        tags: v1, latest
<<<<<<< HEAD
        dockerfile: user-management-service/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
=======
        registry: https://index.docker.io/v1/
        dockerfile: user-management-service/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: user-management-service
>>>>>>> 188b353b03ac240852ef9171d4f70579bd377f37
