name: Build and Tag on Merge to Develop

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  build-and-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: maven

    - name: Build Project
      run: mvn clean install

    - name: Increment version and create tag
      if: success()
      run: |
        # Get the latest tag from git
        latest_tag=$(git tag -l "user-management-service-*" | sort -V | tail -n 1)
        
        # Extract the version number from the latest tag, for example: user-management-service-1.0.1
        version=${latest_tag#user-management-service-}
        
        # Increment the patch version (e.g., 1.0.1 -> 1.0.2)
        IFS='.' read -r major minor patch <<< "$version"
        patch=$((patch + 1))
        new_version="$major.$minor.$patch"
        
        # Create a new tag with the incremented version
        new_tag="user-management-service-$new_version"
        
        # Tag the commit with the new version
        git tag "$new_tag"
        
        # Push the new tag to the remote repository
        git push origin "$new_tag"
        
        # Output the new tag for logging purposes
        echo "Created new tag: $new_tag"
        
